name: Our Workflow
on:
  push:
    branches:
      - 'master'
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout brance
        uses: actions/checkout@v3

      - name: 2. Set up JDK
        uses: actions/setup-java@v3
        with: 
          java-version: 17
          distributtion: 'oracle'

      - name: ls -al 
        run: ls -al
