name: Our Workflow
on:
  push:
    branches:
      - 'master'
  
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:

    # build
      - name: Checkout brance
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: nuxt build

      - name: ls -al
        run: ls -al
      
      - name: ls -al /var/www/moongi-dev
        run: ls -al /var/www/moongi-dev


    # # deploy

    #   - name: Deploy to EC2
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.EC2_HOST }}
    #       username: ${{ secrets.EC2_USERNAME }}
    #       key: ${{ secrets.EC2_PRIVATE_KEY }}
    #       script: | 
    #         cd /var/www/moongi-dev
    #         git pull origin master
    #         npm install
    #         npm run build
    
