name: Our Workflow
on:
  push:
    branches:
      - 'master'
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout brance
        uses: actions/checkout@v3

      - name: 2. Set up JDK
        uses: actions/setup-java@v3
        with: 
          java-version: 17
          distribution: 'oracle'

      - name: ls -al /opt/hostedtoolcache/Java_Oracle_jdk/17/x64
        run: ls -al /opt/hostedtoolcache/Java_Oracle_jdk/17/x64

      - name: Java Version
        run: java -version
