name: Our Workflow
on:
  push:
    branches:
      - 'master'
  
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:

    # build
      - name: Checkout brance
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
          
      - name: Install dependencies
        run: npm install

      - name: yarn -version
        run: yarn -version

      - name: Run build
        run: yarn generate

      - name: ls -al 
        run: ls -al


    # deploy
      - name: Deploy to EC2
        uses: easingthemes/ssh-action@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            cd /var/www/moongi-dev
            ls -al
            # nginx -s reload
    
